# Generated by Django 2.2 on 2019-04-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('REG', 'Regular'), ('VEG', 'Vegetarian'), ('SO', 'Special offer'), ('BABY', 'Baby menu'), ('HOT', 'Hot')], default='REG', max_length=4),
        ),
    ]
